# Generated by Django 3.1.2 on 2020-10-23 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201024_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmoney_info',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='addmoney_info',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
