# Generated by Django 3.1.2 on 2020-10-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_addmoney_info_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmoney_info',
            name='user',
        ),
    ]
