# Generated by Django 3.1.2 on 2020-10-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='savings',
            new_name='Savings',
        ),
    ]
