# Generated by Django 3.1.2 on 2020-10-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201026_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Savings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
