# Generated by Django 3.1.2 on 2020-10-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201026_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
