# Generated by Django 3.1.2 on 2020-10-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201030_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmoney_info',
            name='money',
        ),
        migrations.AlterField(
            model_name='addmoney_info',
            name='add_money',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=10),
        ),
    ]
