# Generated by Django 3.1.2 on 2020-11-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201030_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Saving',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
