# Generated by Django 3.1.2 on 2020-11-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_userprofile_saving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Saving',
        ),
    ]
